version: '3'
services:
  mongodb:
    image: mongo
    expose:
      - '27017'
  web:
    image: node:14-alpine
    working_dir: /app
    restart: on-failure:5
    build:
      context: ./
      dockerfile: ee.Dockerfile
    ports:
      - '1993:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb/eeplus
      newReg: version3
    tty: true
    stdin_open: true
